Update installation instructions to include parler [fix #41]
django-cms/djangocms-alias pull request #104
Opened 2022-04-06 22:26 UTC by marksweb

Updates the installation instructions to include the dependency on parler, fixing #41

2022-04-07 12:19 UTC, Aiky30 requested changes
Needs a changelog entry so that we can track this coming through releases.

2022-04-07 19:39 UTC, marksweb commented
@Aiky30 changelog entry added

2022-04-08 08:12 UTC, Aiky30 commented on CHANGELOG.rst
> +* fix: Added parler to the installation instructions as an installed app
```suggestion
```

2022-04-08 08:15 UTC, Aiky30 requested changes
Hi Mark, 

I think your forked branch was out of date, I've updated the branch rules to force updates to make this easier in future. The changelog is now showing in the released portion. Annoyingly I can't use the GH suggestions to add this back in myself.

2022-04-08 08:15 UTC, Aiky30 commented on CHANGELOG.rst
> +* fix: Added parler to the installation instructions as an installed app
```suggestion
```

Needs moving to the unreleased section, I think the fork you had was not updated.

2022-04-14 07:18 UTC, Aiky30 approved these changes

2022-04-14 07:18 UTC, merged