feat: Add correct icons for the Alias Manager actions
django-cms/djangocms-alias pull request #115
Opened 2022-04-19 14:31 UTC by NarenderRajuB

Add correct icons for the Alias Manager actions: rename alias and change alias settings

2022-04-19 14:43 UTC, adam-murray requested changes
Looks good, could you add a CHANGELOG entry as well?

2022-04-19 14:45 UTC, adam-murray approved these changes

2022-04-19 15:02 UTC, Aiky30 requested changes

2022-04-19 15:02 UTC, Aiky30 commented on CHANGELOG.rst
> +* feat: Add correct icons for Alias Manager actions
```suggestion
* fix: Add correct icons for Alias Manager actions
```

Fix matters for the release number that this will become.

2022-04-20 11:26 UTC, Aiky30 approved these changes

2022-04-20 11:26 UTC, merged