fix: added custom category filter to allow sorting by name
django-cms/djangocms-alias pull request #122
Opened 2022-05-10 10:43 UTC by Bernardvdv

2022-05-12 10:43 UTC, Aiky30 requested changes
Minor changes, smart_text being the biggest

2022-05-12 10:43 UTC, Aiky30 commented on djangocms_alias/admin.py
>      alias_content_admin_list_filter = (SiteFilter, LanguageFilter, UnpublishedFilter)
`alias_content_admin_list_filter` appears to be duplicated historically, we should clean that.

2022-05-12 10:43 UTC, Aiky30 commented on djangocms_alias/admin.py
>      alias_content_admin_list_filter = (SiteFilter, LanguageFilter, UnpublishedFilter)
```suggestion
```

2022-05-12 10:43 UTC, Aiky30 commented on djangocms_alias/filters.py
> +            yield str(obj.pk), smart_text(obj)
smart_text is deprecated in django 3: https://docs.djangoproject.com/en/4.0/releases/3.0/#features-deprecated-in-3-0

some help to replace: https://docs.djangoproject.com/en/3.2/_modules/django/utils/encoding/#smart_text

2022-05-12 10:43 UTC, Aiky30 commented on djangocms_alias/filters.py
> +        cat = Category.objects.filter(pk__in=cat_id).order_by('translations__name')
```suggestion
        # Ensure the category is ordered by the name alphabetically by default
        cat = Category.objects.filter(pk__in=cat_id).order_by('translations__name')
```

Try to add comments to reinforce why something exists.

2022-05-12 12:04 UTC, adam-murray approved these changes

2022-05-13 11:04 UTC, Aiky30 requested changes
2 minor changes for deprecation. You can run the depecation and warnings checks in tests by add ing -Wd to the test parameters.

2022-05-13 11:04 UTC, Aiky30 commented on tests/test_admin_filters.py
> +        self.assertEquals(
assertEquals is deprecated: https://docs.python.org/3/library/unittest.html#deprecated-aliases
```suggestion
        self.assertEqual(
```

2022-05-13 11:04 UTC, Aiky30 commented on tests/test_admin_filters.py
> +        self.assertEquals(
```suggestion
        self.assertEqual(
```

assertEquals is deprecated: https://docs.python.org/3/library/unittest.html#deprecated-aliases

2022-05-13 12:34 UTC, Aiky30 approved these changes

2022-05-13 12:34 UTC, merged