feat: Create plugin alias filter to use category and or site
django-cms/djangocms-alias pull request #125
Opened 2022-05-13 15:21 UTC by Aiky30

2022-05-27 11:43 UTC, Bernardvdv approved these changes

2022-05-30 09:08 UTC, adam-murray commented on tests/test_views.py
> +        The list should be filtered based on only matching
```suggestion
        The list is filtered based on only matching
```

2022-05-30 09:09 UTC, adam-murray commented on tests/test_views.py
> +        The list should be filtered based on only matching
```suggestion
        The list is filtered based on only matching
```

2022-05-30 09:09 UTC, adam-murray commented on tests/test_views.py
> +    def test_select2_view_text_repr(self):
Missing docstring

2022-05-30 09:10 UTC, adam-murray requested changes
Looks good, jsut a couple of minor changes to docstrings in the tests

2022-05-31 09:55 UTC, NarenderRajuB approved these changes
LGTM

2022-05-31 14:47 UTC, Aiky30 commented on tests/test_views.py
> +    def test_select2_view_text_repr(self):
```suggestion
    def test_select2_view_text_repr(self):
        """
        Ensure that the display / text representation of the object
        is output to the user.
        """
```

2022-05-31 15:55 UTC, adam-murray approved these changes

2022-05-31 15:56 UTC, merged