fix djangocms-versioning draft deletion bug (#214)
django-cms/djangocms-alias pull request #215
Opened 2024-01-29 11:49 UTC by fscherf

Previously, `djangocms_alias.models.AliasContent.delete` deleted all plugins related to `AliasContent.alias`, with the same language. Drafts and previously published versions included.
This meant that the deletion of a draft resulted in plugins disappearing from published pages.

This patch removes the mechanism entirely and instead adds a warning, notifying the user that the last version or translation of a language got deleted.

2024-01-30 07:20 UTC, fsbraun requested changes
@fscherf Thanks for the pull request! 

I've added two comments. Can I ask you to create a test for the behaviour, including the scenario without a message: Delete a draft when a published version is there?

2024-01-30 07:20 UTC, fsbraun commented on djangocms_alias/admin.py
> +        if obj.alias.contents.filter(language=obj.language).count() == 1:
I'm not sure if that condition is correct. If verisoning is stalled, `alias.contents` will give published results only.

```suggestion
        if obj.alias._default_manager.filter(language=obj.language).count() == 1:
```

2024-02-05 17:43 UTC, fscherf commented
@fsbraun: Is there anything else that I can do?

2024-02-12 09:47 UTC, fscherf commented
@fsbraun: What is the state of this PR? Can it be merged?

2024-02-12 09:48 UTC, fsbraun commented
@fscherf LGTM! I will give it a test asap and merge afterwards!

2024-02-12 10:30 UTC, fsbraun commented
So, tests should pass again!

2024-02-12 11:18 UTC, fsbraun commented
@fscherf I can confirm, that deleting the alias draft does not remove all connected alias plugins. However, I fail to get the new message. Can you point me to where I should be seeing this?

2024-02-12 12:36 UTC, fscherf commented
@fsbraun: Ah! It seems, the message is not shown when using djangocms-versioning, because it overrides the delete method.

2024-02-13 14:39 UTC, fscherf commented
@fsbraun: It works, but the message does not show up in all cases. Is that enough, or do we need to change plans here?

2024-02-27 14:37 UTC, fscherf commented
What's the state of this PR?

2024-03-10 13:23 UTC, fsbraun approved these changes

2024-03-10 13:25 UTC, merged