Update pre-commit checks
django-cms/djangocms-alias pull request #217
Opened 2024-02-04 16:12 UTC by raffaellasuardini

- updated .pre-commit-config.yaml: inserted ruff and pre-commit hooks

- created Ruff configuratio in pyproject.toml

2024-02-05 01:40 UTC, marksweb requested changes

2024-02-05 01:40 UTC, marksweb commented on djangocms_alias/constants.py
> +DELETE_ALIAS_URL_NAME = f"{PLUGIN_URL_NAME_PREFIX}_delete"
This gets redefined further down, so can we delete `DELETE_ALIAS_URL_NAME` from line 5 please?

2024-02-05 02:17 UTC, marksweb commented
The test failures might be a clue as to a change.

For the most part it's a case of `this string\n` in the test being asserted as `this string` so perhaps something in the test setup that's causing a newline character.

2024-02-05 02:18 UTC, marksweb commented
@fsbraun If you've got some time, could you take a look and see if I'm missing something with the tests?

2024-02-05 10:26 UTC, fsbraun commented on djangocms_alias/test_utils/text/templates/text/text.html
> +{{ instance.body|safe }}
Here, a newline has been added which must be removed. Sometimes editors do this. I have this issue with PyCharm, for example.

2024-02-05 11:29 UTC, fsbraun commented on djangocms_alias/test_utils/text/templates/text/text.html
> +{{ instance.body|safe }}
Ah, there we go. I'll also have to do this for djanogcms-text[-ckeditor]...

2024-02-09 13:49 UTC, marksweb approved these changes

2024-02-09 13:53 UTC, merged